name = "my-simple-saas"
compatibility_date = "2026-01-08"
pages_build_output_dir = "public"

[[d1_databases]]
binding = "DB"
database_name = "my-db"
database_id = "your-id-here" # Для локальної розробки це значення може бути будь-яким